name: Test JSON schema transforation in container 

on: [push, pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch container
        run: |
          docker pull quay.io/ebigxa/json_schema_transform
      - name: Run test script
        run: |
          run_tests.sh  

