name: Test JSON schema transforation in container 

on: [push, pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull quay.io/ebigxa/json_schema_transform
      - run: ./run_tests.sh  



