name: Test JSON schema transforation in container 

on: [push, pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ebigxa/json_schema_transform
    steps:
      - uses: actions/checkout@v2
      - name: Add workspace to path
        run: |
          echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - name: Run test script
        run: |
          run_tests.sh  

